flutter:
  uses-material-design: true

  # ==== تم تصحيح جميع المسارات هنا ====
  assets:
    - asset/images/
    - asset/design_course/
    - asset/fitness_app/
    - asset/hotel/
    - asset/introduction_animation/

  fonts:
    - family: Cairo
      fonts:
        - asset: asset/fonts/Cairo-Regular.ttf
        - asset: asset/fonts/Cairo-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: asset/fonts/Roboto-Regular.ttf
        - asset: asset/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: asset/fonts/Roboto-Bold.ttf
          weight: 700
