name: best_flutter_ui_templates
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0" # نطاق أوسع وأفضل للتوافق

dependencies:
  flutter:
    sdk: flutter

  # المكتبات الأساسية التي كانت موجودة
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  flutter_rating_bar: ^4.0.1
  intl: ^0.19.0 # تم تحديثه ليتوافق مع الإصدارات الجديدة
  animations: ^2.0.11

  # ==== المكتبات المفقودة التي تسببت في كل الأخطاء (تمت إضافتها) ====
  flutter_slidable: ^3.1.0
  sqflite: ^2.4.2
  pdf: ^3.11.0
  printing: ^5.12.0
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  file_picker: ^10.3.3
  # =================================================================

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0 # تم تحديثه

flutter:
  uses-material-design: true



  fonts:
    - family: Cairo
      fonts:
        - asset: asset/fonts/Cairo-Regular.ttf
        - asset: asset-fonts/Cairo-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: asset/fonts/Roboto-Bold.ttf
        - asset: asset/fonts/Roboto-Regular.ttf
        - asset: asset/fonts/Roboto-Medium.ttf
          weight: 400
