name: best_flutter_ui_templates
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # الأيقونات
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0

  # UI والرسوم المتحركة
  flutter_rating_bar: ^4.0.1
  animations: ^2.0.11
  flutter_slidable: ^3.1.1

  # التاريخ والوقت
  intl: ^0.19.0

  # قاعدة البيانات
  # --- هذا هو السطر الذي تم تعديله ---
  # تم تخفيض الإصدار ليتوافق مع Dart 3.4.3
  sqflite: ^2.3.3 

  # PDF والطباعة
  pdf: ^3.11.1
  printing: ^5.13.4

  # المشاركة والملفات
  share_plus: ^10.1.2
  path_provider: ^2.1.5
  path: ^1.9.0
  file_picker: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # هذا التعديل من المرة السابقة
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - asset/fonts/

  # fonts:
  #   - family: Cairo
  #     fonts:
  #       - asset: asset/fonts/Cairo-Regular.ttf
  #       - asset: asset/fonts/Cairo-Bold.ttf
  #         weight: 700

