name: best_flutter_ui_templates
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

# ==== هذا هو القسم الذي تم حذفه بالخطأ ====
environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # الأيقونات
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0

  # UI والرسوم المتحركة
  flutter_rating_bar: ^4.0.1
  animations: ^2.0.11
  flutter_slidable: ^3.1.0

  # التاريخ والوقت
  intl: ^0.19.0

  # قاعدة البيانات
  sqflite: ^2.3.3+1
  path: ^1.9.0

  # PDF والطباعة
  pdf: ^3.11.1
  printing: ^5.12.0

  # المشاركة والملفات
  share_plus: ^7.2.2
  path_provider: ^2.1.3
  file_picker: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # تأكد من أن اسم هذا المجلد يطابق ما لديك (asset أو assets)
  assets:
    - asset/images/
    - asset/design_course/
    - asset/fitness_app/
    - asset/hotel/
    - asset/introduction_animation/
    - asset/fonts/

  fonts:
    - family: Cairo
      fonts:
        - asset: asset/fonts/Cairo-Regular.ttf
        - asset: asset/fonts/Cairo-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: asset/fonts/Roboto-Regular.ttf
        - asset: asset/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: asset/fonts/Roboto-Bold.ttf
          weight: 700
