name: Build Flutter APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'
        channel: 'stable'
        cache: true
    
    - name: Create local.properties
      run: |
        echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
        echo "sdk.dir=$ANDROID_SDK_ROOT" >> android/local.properties
    
    - name: Flutter Doctor
      run: flutter doctor -v

    # --- هذه هي الخطوة الجديدة المضافة ---
    - name: Accept Android Licenses
      # هذا الأمر سيقوم بقبول التراخيص تلقائياً بدلاً من السؤال
      run: yes | flutter doctor --android-licenses
    
    - name: Clean Project
      run: flutter clean
    
    - name: Get Dependencies
      run: flutter pub get
    
    - name: Build APK
      run: flutter build apk --release --no-shrink
    
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
        retention-days: 30

