name: Dart CI

on:
  push:
    branches: [ master ] # أو "main" حسب اسم الفرع الرئيسي لديك

env:
  # يمكنك إزالة هذه المتغيرات لأنك تحددها في الخطوات التالية
  # flutter_channel: 'stable'
  # flutter_version: '3.32.7'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install dependencies
        run: flutter pub get
      
      # - run: flutter test # يمكنك تفعيله لاحقاً إذا أضفت اختبارات

      - name: Build Release APK
        # === التعديل المهم هنا ===
        run: flutter build apk --release 

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk # المسار الصحيح غالباً
