name: ุชุดุฎูุต ูุฅุตูุงุญ ุงููุดุฑูุน

on:
  workflow_dispatch:
  
jobs:
  diagnose:
    runs-on: ubuntu-latest
    
    steps:
    - name: ุงุณุชูุณุงุฎ ุงููุณุชูุฏุน
      uses: actions/checkout@v4
      
    - name: ุฅุนุฏุงุฏ Java (JDK 17)
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: ุฅุนุฏุงุฏ Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
        
    - name: ุฅุนุฏุงุฏ Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 33
        build-tools: 33.0.2
        target: 'default'
        
    - name: ุชุซุจูุช ุชุฑุงุฎูุต Android
      run: |
        echo "y" | sdkmanager --licenses
        echo "y" | sdkmanager --licenses all
        
    - name: ูุญุต ุงูุจูุฆุฉ
      run: |
        echo "=== ูุญุต ุฅุตุฏุงุฑ Flutter ==="
        flutter --version
        
        echo ""
        echo "=== ูุญุต ุงูููููุงุช ==="
        flutter doctor -v
        
        echo ""
        echo "=== ูุญุต Android SDK ==="
        sdkmanager --list | head -10
        
    - name: ูุญุต ููู pubspec.yaml
      run: |
        echo "=== ูุญุต ููู pubspec.yaml ==="
        if [ -f "pubspec.yaml" ]; then
          echo "โ ููู pubspec.yaml ููุฌูุฏ"
          echo ""
          echo "ูุญุชูู ุงูููู:"
          cat pubspec.yaml
        else
          echo "โ ููู pubspec.yaml ุบูุฑ ููุฌูุฏ"
          exit 1
        fi
        
    - name: ูุญุต ุจููุฉ ุงููุดุฑูุน
      run: |
        echo "=== ูุญุต ุจููุฉ ุงููุดุฑูุน ==="
        echo ""
        echo "๐ ูุญุชููุงุช ุงููุฌูุฏ:"
        find . -type f -name "*.dart" | head -20
        
        echo ""
        echo "๐ ูุฌูุฏ android:"
        if [ -d "android" ]; then
          echo "โ ูุฌูุฏ android ููุฌูุฏ"
          ls -la android/
        else
          echo "โ ูุฌูุฏ android ุบูุฑ ููุฌูุฏ"
          exit 1
        fi
        
        echo ""
        echo "๐ ูุฌูุฏ lib:"
        if [ -d "lib" ]; then
          echo "โ ูุฌูุฏ lib ููุฌูุฏ"
          ls -la lib/
        else
          echo "โ ูุฌูุฏ lib ุบูุฑ ููุฌูุฏ"
          exit 1
        fi
        
    - name: ุชุซุจูุช ุงูุชุจุนูุงุช
      run: |
        echo "=== ุชุซุจูุช ุงูุชุจุนูุงุช ==="
        flutter pub get
        echo "โ ุชู ุชุซุจูุช ุงูุชุจุนูุงุช ุจูุฌุงุญ"
        
    - name: ูุญุต ุงูููุฏ
      run: |
        echo "=== ูุญุต ุงูููุฏ ==="
        flutter analyze
        
    - name: ุชูุธูู ูุฅุนุงุฏุฉ ุงูุจูุงุก
      run: |
        echo "=== ุชูุธูู ุงูุจูุงุก ุงูุณุงุจู ==="
        flutter clean
        
        echo ""
        echo "=== ุฅุนุงุฏุฉ ุชุซุจูุช ุงูุชุจุนูุงุช ==="
        flutter pub get
        
        echo ""
        echo "=== ูุญุต ุงูุฃุฎุทุงุก ==="
        flutter analyze
        
    - name: ุฅูุดุงุก ุชูุฑูุฑ ุงูุชุดุฎูุต
      run: |
        echo "# ุชูุฑูุฑ ุชุดุฎูุต ุชุทุจูู ุงูููุงุชูุฑ" > diagnostic-report.md
        echo "" >> diagnostic-report.md
        echo "**ุชุงุฑูุฎ ุงูุชุดุฎูุต:** $(date)" >> diagnostic-report.md
        echo "**ูุฑุน ุงููุณุชูุฏุน:** ${{ github.ref_name }}" >> diagnostic-report.md
        echo "**ุฑูู ุงูุชุญุฏูุซ:** ${{ github.run_number }}" >> diagnostic-report.md
        echo "" >> diagnostic-report.md
        echo "## ูุชุงุฆุฌ ุงูุชุดุฎูุต" >> diagnostic-report.md
        echo "" >> diagnostic-report.md
        
        echo "### โ ูุญุต ุงูุจูุฆุฉ" >> diagnostic-report.md
        echo "- Flutter SDK: 3.24.5" >> diagnostic-report.md
        echo "- JDK: 17" >> diagnostic-report.md
        echo "- Android SDK API: 33" >> diagnostic-report.md
        echo "- Build Tools: 33.0.2" >> diagnostic-report.md
        echo "" >> diagnostic-report.md
        
        echo "### โ ูุญุต ุงููุดุฑูุน" >> diagnostic-report.md
        echo "- pubspec.yaml: ููุฌูุฏ โ" >> diagnostic-report.md
        echo "- ูุฌูุฏ android: ููุฌูุฏ โ" >> diagnostic-report.md
        echo "- ูุฌูุฏ lib: ููุฌูุฏ โ" >> diagnostic-report.md
        echo "- ุงูุชุจุนูุงุช: ููุซุจุชุฉ ุจูุฌุงุญ โ" >> diagnostic-report.md
        echo "" >> diagnostic-report.md
        
        echo "## ุงูุชูุตูุงุช" >> diagnostic-report.md
        echo "" >> diagnostic-report.md
        echo "1. โ ุงููุดุฑูุน ุฌุงูุฒ ููุจูุงุก" >> diagnostic-report.md
        echo "2. ๐ ููููู ุงูุขู ุชุดุบูู workflow ุจูุงุก APK" >> diagnostic-report.md
        echo "3. ๐ฑ ุงุฎุชุฑ ููุน ุงูุจูุงุก (debug/release) ุญุณุจ ุงูุญุงุฌุฉ" >> diagnostic-report.md
        echo "4. โก ุงุฎุชุฑ ููุน ุงููุนุงูุฌ ุงูููุงุณุจ ูุฌูุงุฒู" >> diagnostic-report.md
        
    - name: ุฑูุน ุชูุฑูุฑ ุงูุชุดุฎูุต
      uses: actions/upload-artifact@v4
      with:
        name: diagnostic-report
        path: diagnostic-report.md
        retention-days: 30
        
    - name: ุฑุณุงูุฉ ุงููุชูุฌุฉ
      run: |
        if [ $? -eq 0 ]; then
          echo "๐ ุชู ุงูุชุดุฎูุต ุจูุฌุงุญ!"
          echo ""
          echo "โ ุงููุดุฑูุน ุฌุงูุฒ ููุจูุงุก"
          echo "๐ ููููู ุงูุขู ุชุดุบูู workflow ุจูุงุก APK"
          echo ""
          echo "๐ ุฎุทูุงุช ูุชุชุงููุฉ:"
          echo "1. ุงูุชูู ุฅูู ุชุจููุจ 'Actions'"
          echo "2. ุงุฎุชุฑ 'ุจูุงุก ุชุทุจูู ุงูููุงุชูุฑ - APK'"
          echo "3. ุงุถุบุท 'Run workflow'"
          echo "4. ุงุฎุชุฑ ููุน ุงูุจูุงุก ูุงููุนุงูุฌ"
          echo "5. ุงุถุบุท 'Run workflow' ูุฑุฉ ุฃุฎุฑู"
        else
          echo "โ ุชู ุงูุนุซูุฑ ุนูู ูุดุงูู ูู ุงูุชุดุฎูุต"
          echo ""
          echo "๐ง ูุฑุงุฌุนุฉ ุงูุชูุฑูุฑ ููุฒูุฏ ูู ุงูุชูุงุตูู"
        fi